name: Rescale images

on:
  push:
    branches:
      - main

jobs:
  rescale:
    name: Resize images
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Resize 2021 images
      uses: xprilion/img-resizer-inplace@v1
      with:
        target: '2021'
        dimensions: 1024x
    #- name: Resize 2022 images
    #  uses: xprilion/img-resizer-inplace@v1
    #  with:
    #    target: '2022'
    #    dimensions: 1024x
    - name: Test
      uses: DavidS/jekyll-deploy@1.1.1
      with:
        build-only: true
      env:
        JEKYLL_ENV: production
        GH_PAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
