name: Rescale images

on:
  push:
    branches:
      - main
      - new_resizer

jobs:
  rescale:
    name: Resize images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        year:
          - '2022'
          - '2023'
          - '2024'
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Resize ${{ matrix.year }} images
      uses: gonzalonaveira/gh-image-resizing@v1.0.2
      with:
        IMAGES_MAX_WIDTH: "1024"
        IMAGES_QUALITY: "100"
        IMAGES_FORMATS: "jpg, jpge, png"
        IMAGES_DIRECTORIES: ${{ matrix.year }}
    - name: Commit files
      run: |
        if [ -z "$(git status --porcelain)" ]; then exit 0;fi
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add ${{ matrix.year }}
        git commit -m "Rescaled ${{ matrix.year }} images"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
